package com.dbbest.databasemanager.loadingmanager.constants.attributes;

public enum  ColumnAttributes {
    COLUMN_TABLE_CATALOG("TABLE_CATALOG"), COLUMN_TABLE_SCHEMA("TABLE_SCHEMA"), COLUMN_TABLE_NAME("TABLE_NAME"), COLUMN_NAME("COLUMN_NAME"), COLUMN_ORDINAL_POSITION("ORDINAL_POSITION"),
    COLUMN_DEFAULT("COLUMN_DEFAULT"), COLUMN_IS_NULLABLE("IS_NULLABLE"), COLUMN_DATA_TYPE("DATA_TYPE"), COLUMN_CHARACTER_MAXIMUM_LENGTH("CHARACTER_MAXIMUM_LENGTH"), COLUMN_CHARACTER_OCTET_LENGTH("CHARACTER_OCTET_LENGTH"),
    COLUMN_NUMERIC_PRECISION("NUMERIC_PRECISION"), COLUMN_NUMERIC_SCALE("NUMERIC_SCALE"), COLUMN_DATETIME_PRECISION("DATETIME_PRECISION"), COLUMN_CHARACTER_SET_NAME("CHARACTER_SET_NAME"),
    COLUMN_COLLATION_NAME("COLLATION_NAME"), COLUMN_TYPE("COLUMN_TYPE"), COLUMN_KEY("COLUMN_KEY"), COLUMN_EXTRA("EXTRA"), COLUMN_PRIVILEGES("PRIVILEGES"), COLUMN_COMMENT("COLUMN_COMMENT"),
    COLUMN_GENERATION_EXPRESSION("GENERATION_EXPRESSION");

    private String element;

    ColumnAttributes(String element) {
        this.element = element;
    }

    public String getElement() {
        return element;
    }
}
