package com.dbbest.databasemanager.loadingmanager.constants.attributes;

public enum StoredProceduresAndFunctionsAttributes {
    SPECIFIC_NAME("SPECIFIC_NAME"), ROUTINE_CATALOG("ROUTINE_CATALOG"), ROUTINE_SCHEMA("ROUTINE_SCHEMA"), ROUTINE_NAME("ROUTINE_NAME"),
    ROUTINE_TYPE("ROUTINE_TYPE"), DATA_TYPE("DATA_TYPE"), CHARACTER_MAXIMUM_LENGTH("CHARACTER_MAXIMUM_LENGTH"),
    CHARACTER_OCTET_LENGTH("CHARACTER_OCTET_LENGTH"), NUMERIC_PRECISION("NUMERIC_PRECISION"), NUMERIC_SCALE("NUMERIC_SCALE"),
    DATETIME_PRECISION("DATETIME_PRECISION"), CHARACTER_SET_NAME("CHARACTER_SET_NAME"), COLLATION_NAME("COLLATION_NAME"),
    DTD_IDENTIFIER("DTD_IDENTIFIER"), ROUTINE_BODY("ROUTINE_BODY"), ROUTINE_DEFINITION("ROUTINE_DEFINITION"), EXTERNAL_NAME("EXTERNAL_NAME"),
    EXTERNAL_LANGUAGE("EXTERNAL_LANGUAGE"), PARAMETER_STYLE("PARAMETER_STYLE"), IS_DETERMINISTIC("IS_DETERMINISTIC"), SQL_DATA_ACCESS("SQL_DATA_ACCESS"),
    SQL_PATH("SQL_PATH"), SECURITY_TYPE("SECURITY_TYPE"), CREATED("CREATED"), LAST_ALTERED("LAST_ALTERED"), SQL_MODE("SQL_MODE"), ROUTINE_COMMENT("ROUTINE_COMMENT"),
    DEFINER("DEFINER"), CHARACTER_SET_CLIENT("CHARACTER_SET_CLIENT"), COLLATION_CONNECTION("COLLATION_CONNECTION"), DATABASE_COLLATION("DATABASE_COLLATION");

    private String element;

    StoredProceduresAndFunctionsAttributes(String element) {
        this.element = element;
    }

    public String getElement() {
        return element;
    }
}
